version: '3'

services:

  code-server:
    image: linuxserver/code-server
    container_name: code-server
    env_file: .code.env
    environment:
      - PUID=82
      - PGID=82
      - TZ=Asia/Seoul
    volumes:
      - ./code-server-data/code-server1_8443/config:/config
    ports:
      - 8443:8443
    restart: unless-stopped
  # nginx:
  #   image: nginx:alpine
  #   container_name: nginx
  #   restart: unless-stopped
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./site:/var/www/html
  #     - ./nginx/conf.d:/etc/nginx/conf.d
  #     # - ./nginx/nginx.conf:/etc/nginx/nginx.conf/
  #     - ./nginx/logs:/var/log/nginx/
  #     - /etc/localtime:/etc/localtime:ro
  #     - /etc/timezone:/etc/timezone:ro

  # certbot:
  #   image: certbot/certbot:latest
  #   container_name: certbot
  #   volumes:
  #     - ./ssl/:/etc/letsencrypt/
  #     - ./usr/share/nginx/html:/usr/share/nginx/html
  #     # - /usr/share/nginx/html:/usr/share/nginx/html
  #     # command: certonly -n --webroot -w /usr/share/nginx/html -d code.wookingwoo.com
  #   command: certonly --dry-run -n --webroot -w /usr/share/nginx/html -d code.wookingwoo.com
