version: '3'

services:

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./site:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
      # - ./nginx/nginx.conf:/etc/nginx/nginx.conf/
      - ./nginx/logs:/var/log/nginx/
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  code-server:
    image: linuxserver/code-server
    container_name: code-server
    env_file: .code.env
    environment:
      - PUID=82
      - PGID=82
      - TZ=Asia/Seoul
    volumes:
      - ./data/code-server:/config
      - ./site:/config/site
    ports:
      - 8443:8443
    restart: unless-stopped
