version: '3'

services:

  code-server:
    image: linuxserver/code-server
    container_name: code-server
    env_file: .code.env
    environment:
      - PUID=82
      - PGID=82
      - TZ=Asia/Seoul
    volumes:
      - ./data/code-server:/config
      - ./site:/config/site
    ports:
      - 8443:8443
    restart: unless-stopped
